import 'dart:io';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:stelacom_check/models/netsuite_device_item.dart';
import 'package:syncfusion_flutter_xlsio/xlsio.dart' as xlsio;

class VerificationReportService {
  static const String RECIPIENT_EMAIL = 'adeeshataxila@gmail.com';
  // static const String RECIPIENT_EMAIL = 'chamarak@stelacom.com';

  /// Generate Excel report using Syncfusion
  static Future<File> generateExcelReport({
    required List<NetsuiteDeviceItem> deviceList,
    required String locationName,
    required String username,
    String? additionalNotes,
  }) async {
    // Create a new Excel document
    final xlsio.Workbook workbook = xlsio.Workbook();
    final xlsio.Worksheet sheet = workbook.worksheets[0];

    sheet.name = 'Verification Report';

    // Set column widths using setColumnWidth method
    sheet.setColumnWidthInPixels(1, 40); // Column A - No.
    sheet.setColumnWidthInPixels(2, 80); // Column B - Item Code
    sheet.setColumnWidthInPixels(3, 200); // Column C - Model
    sheet.setColumnWidthInPixels(4, 250); // Column D - Item Category
    sheet.setColumnWidthInPixels(5, 120); // Column E - Number/IMEI/Serial
    sheet.setColumnWidthInPixels(6, 60); // Column F - Serialized
    sheet.setColumnWidthInPixels(7, 100); // Column G - Expected Quantity
    sheet.setColumnWidthInPixels(8, 100); // Column H - Actual Quantity
    sheet.setColumnWidthInPixels(9, 100); // Column I - Verification Status
    sheet.setColumnWidthInPixels(10, 150); // Column J - Variance Reason
    sheet.setColumnWidthInPixels(11, 120); // Column K - Verification Time

    // Title Section
    sheet.getRangeByName('A1:K1').merge();
    sheet.getRangeByName('A1').setText('Device Verification Report');
    sheet.getRangeByName('A1').cellStyle.bold = true;
    sheet.getRangeByName('A1').cellStyle.fontSize = 16;
    sheet.getRangeByName('A1').cellStyle.backColor = '#2E5C8A';
    sheet.getRangeByName('A1').cellStyle.fontColor = '#FFFFFF';
    sheet.getRangeByName('A1').cellStyle.hAlign = xlsio.HAlignType.center;
    sheet.getRangeByName('A1').cellStyle.vAlign = xlsio.VAlignType.center;
    sheet.getRangeByName('A1').rowHeight = 25;

    // Merge empty row 2 (D2:F2)
    sheet.getRangeByName('D2:G2').merge();

    // Report Info Section (positioned in the middle columns D-E)
    int currentRow = 3;

    // Report Date (merge D3:F3)
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet
        .getRangeByIndex(currentRow, 4)
        .setText(
          'Report Date: ${DateFormat('yyyy-MM-dd HH:mm:ss').format(DateTime.now())}',
        );
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Generated By (merge D4:F4)
    currentRow++;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet.getRangeByIndex(currentRow, 4).setText('Generated By: $username');
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Location (merge D5:F5)
    currentRow++;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet.getRangeByIndex(currentRow, 4).setText('Location: $locationName');
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Total Items (merge D6:F6)
    currentRow++;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet
        .getRangeByIndex(currentRow, 4)
        .setText('Total Items: ${deviceList.length}');
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Verified Items (merge D7:F7)
    currentRow++;
    int verifiedCount = deviceList.where((item) => item.isVerified).length;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet
        .getRangeByIndex(currentRow, 4)
        .setText('Verified Items: $verifiedCount');
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Unverified Items (merge D8:F8)
    currentRow++;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    sheet
        .getRangeByIndex(currentRow, 4)
        .setText('Unverified Items: ${deviceList.length - verifiedCount}');
    sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
    sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
        xlsio.HAlignType.center;

    // Merge empty row 9 (D9:F9)
    currentRow++;
    sheet.getRangeByName('D$currentRow:G$currentRow').merge();

    // Additional Notes (merge D and E columns, centered)
    if (additionalNotes != null && additionalNotes.isNotEmpty) {
      currentRow++;
      sheet.getRangeByName('D$currentRow:G$currentRow').merge();
      sheet
          .getRangeByIndex(currentRow, 4)
          .setText('Additional Notes: $additionalNotes');
      sheet.getRangeByIndex(currentRow, 4).cellStyle.bold = true;
      sheet.getRangeByIndex(currentRow, 4).cellStyle.hAlign =
          xlsio.HAlignType.center;
      sheet.getRangeByIndex(currentRow, 4).cellStyle.wrapText = true;

      // Merge empty row after additional notes
      currentRow++;
      sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    } else {
      // If no additional notes, merge the row where it would have been
      currentRow++;
      sheet.getRangeByName('D$currentRow:G$currentRow').merge();
    }

    // Table Headers
    currentRow++;
    // int headerRow = currentRow; // Store header row position
    List<String> headers = [
      'No.',
      'Item Code',
      'Item',
      'Item Category',
      'Number/IMEI/Serial',
      'Serialized',
      'Expected Quantity',
      'Actual Quantity',
      'Verification Status',
      'Variance Reason/Notes',
      'Verification Time',
    ];

    xlsio.Style headerStyle = workbook.styles.add('HeaderStyle');
    headerStyle.bold = true;
    headerStyle.fontSize = 11;
    headerStyle.backColor = '#4472C4';
    headerStyle.fontColor = '#FFFFFF';
    headerStyle.hAlign = xlsio.HAlignType.center;
    headerStyle.vAlign = xlsio.VAlignType.center;
    // Add borders to header style
    headerStyle.borders.all.lineStyle = xlsio.LineStyle.thin;
    headerStyle.borders.all.color = '#CCCCCC';

    for (int i = 0; i < headers.length; i++) {
      sheet.getRangeByIndex(currentRow, i + 1).setText(headers[i]);
      sheet.getRangeByIndex(currentRow, i + 1).cellStyle = headerStyle;
    }

    // Data Rows
    currentRow++;

    xlsio.Style verifiedStyle = workbook.styles.add('VerifiedStyle');
    verifiedStyle.backColor = '#C6EFCE';
    verifiedStyle.fontColor = '#006100';
    // Add borders to verified style
    verifiedStyle.borders.all.lineStyle = xlsio.LineStyle.thin;
    verifiedStyle.borders.all.color = '#CCCCCC';

    xlsio.Style unverifiedStyle = workbook.styles.add('UnverifiedStyle');
    unverifiedStyle.backColor = '#FFC7CE';
    unverifiedStyle.fontColor = '#9C0006';
    // Add borders to unverified style
    unverifiedStyle.borders.all.lineStyle = xlsio.LineStyle.thin;
    unverifiedStyle.borders.all.color = '#CCCCCC';

    for (int i = 0; i < deviceList.length; i++) {
      NetsuiteDeviceItem item = deviceList[i];
      xlsio.Style rowStyle = item.isVerified ? verifiedStyle : unverifiedStyle;

      // No.
      sheet.getRangeByIndex(currentRow, 1).setNumber((i + 1).toDouble());
      sheet.getRangeByIndex(currentRow, 1).cellStyle = rowStyle;

      // Item Code
      sheet.getRangeByIndex(currentRow, 2).setText(item.itemCode);
      sheet.getRangeByIndex(currentRow, 2).cellStyle = rowStyle;

      // Model
      sheet.getRangeByIndex(currentRow, 3).setText(item.item);
      sheet.getRangeByIndex(currentRow, 3).cellStyle = rowStyle;

      // Category
      sheet.getRangeByIndex(currentRow, 4).setText(item.itemCategory);
      sheet.getRangeByIndex(currentRow, 4).cellStyle = rowStyle;

      // Number/IMEI/Serial
      sheet
          .getRangeByIndex(currentRow, 5)
          .setText(item.isSerialized ? (item.serialNumber ?? 'N/A') : 'N/A');
      sheet.getRangeByIndex(currentRow, 5).cellStyle = rowStyle;

      // Serialized
      sheet
          .getRangeByIndex(currentRow, 6)
          .setText(item.isSerialized ? 'Yes' : 'No');
      sheet.getRangeByIndex(currentRow, 6).cellStyle = rowStyle;

      // Expected Quantity
      if (item.isSerialized) {
        sheet.getRangeByIndex(currentRow, 7).setNumber(1);
      } else if (item.quantity != null) {
        sheet
            .getRangeByIndex(currentRow, 7)
            .setNumber(item.quantity!.toDouble());
      } else {
        sheet.getRangeByIndex(currentRow, 7).setText('-');
      }
      sheet.getRangeByIndex(currentRow, 7).cellStyle = rowStyle;
      sheet.getRangeByIndex(currentRow, 7).cellStyle.hAlign =
          xlsio.HAlignType.center;

      // Actual Quantity
      if (item.isSerialized) {
        sheet.getRangeByIndex(currentRow, 8).setNumber(item.isVerified ? 1 : 0);
      } else {
        sheet
            .getRangeByIndex(currentRow, 8)
            .setNumber(item.quantityVerified.toDouble());
      }
      sheet.getRangeByIndex(currentRow, 8).cellStyle = rowStyle;
      sheet.getRangeByIndex(currentRow, 8).cellStyle.hAlign =
          xlsio.HAlignType.center;

      // Verification Status
      sheet
          .getRangeByIndex(currentRow, 9)
          .setText(item.isVerified ? 'Verified' : 'Unverified');
      sheet.getRangeByIndex(currentRow, 9).cellStyle = rowStyle;

      // Variance Reason
      sheet.getRangeByIndex(currentRow, 10).setText(item.varianceReason ?? '-');
      sheet.getRangeByIndex(currentRow, 10).cellStyle = rowStyle;
      sheet.getRangeByIndex(currentRow, 10).cellStyle.wrapText = true;

      // Verification Time
      String verificationTime = item.verificationTime != null
          ? DateFormat('yyyy-MM-dd HH:mm:ss').format(item.verificationTime!)
          : '-';
      sheet.getRangeByIndex(currentRow, 11).setText(verificationTime);
      sheet.getRangeByIndex(currentRow, 11).cellStyle = rowStyle;

      currentRow++;
    }

    // Auto-fit rows
    for (int i = 1; i <= currentRow; i++) {
      sheet.autoFitRow(i);
    }

    // Save to file
    final List<int> bytes = workbook.saveAsStream();
    workbook.dispose();

    String timestamp = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
    String fileName = 'Verification_Report_${locationName}_$timestamp.xlsx';

    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/$fileName');
    await file.writeAsBytes(bytes, flush: true);

    return file;
  }

  /// Send verification report email using flutter_email_sender
  static Future<bool> sendVerificationEmail({
    required File excelFile,
    required String locationDescription,
    required int verifiedCount,
    required int totalCount,
    required String username,
    String? additionalNotes,
  }) async {
    try {
      int unverifiedCount = totalCount - verifiedCount;
      double completionRate = totalCount > 0
          ? (verifiedCount / totalCount * 100)
          : 0;
      String timestamp = DateFormat(
        'MMMM dd, yyyy - HH:mm:ss',
      ).format(DateTime.now());

      // Create email body
      String emailBody =
          '''
Device Verification Report
iCheck Stelacom Verification System

────────────────────────────────────────────

📍 Location: $locationDescription
👤 Verified By: $username
📅 Report Generated: $timestamp

────────────────────────────────────────────

VERIFICATION SUMMARY:
✅ Verified: $verifiedCount items
❌ Unverified: $unverifiedCount items
📊 Total Items: $totalCount items
📈 Completion Rate: ${completionRate.toStringAsFixed(1)}%

────────────────────────────────────────────
${additionalNotes != null && additionalNotes.isNotEmpty ? '\n📝 ADDITIONAL NOTES:\n$additionalNotes\n\n────────────────────────────────────────────\n' : ''}
🔎 ATTACHMENT:
Please find the detailed verification report in the attached Excel file.

The file contains complete information about all devices including:
• Item codes and model numbers
• Serial numbers / IMEI numbers
• Expected and Actual quantities for non-serialized items
• Verification status for each device
• Variance reasons (if any)
• Verification timestamps

────────────────────────────────────────────

This is an automated email from StelacomCheck Verification System
© ${DateTime.now().year} StelacomCheck. All rights reserved.
      ''';

      final Email email = Email(
        body: emailBody,
        subject:
            'Device Verification Report - Location: $locationDescription - ${DateFormat('yyyy-MM-dd').format(DateTime.now())}',
        recipients: [RECIPIENT_EMAIL],
        attachmentPaths: [excelFile.path],
        isHTML: false,
      );

      await FlutterEmailSender.send(email);
      return true;
    } catch (e) {
      print('Error sending email: $e');
      return false;
    }
  }
}
