import 'package:flutter/material.dart';

final cameraCaptureBtnTextColor = Colors.red[700];
final appbarBgColor = Colors.red.shade50;
// final screenHeadingColor = Colors.deepOrange.shade800;
final screenHeadingColor = Colors.orange.shade900;
final iconColors = Colors.orange.shade900;
final numberColors = Colors.deepOrange.shade800;
final sliderButtonBgColor = Colors.deepOrange.shade700.withOpacity(0.9);
final boxBgColor = Colors.orange[50];
final cardColros = Colors.grey.shade50;
final appBgColor = Colors.grey[50];
final normalTextColor = Colors.black;
final actionBtnTextColor = Colors.white;
final actionBtnColor = Color(0xFFFF9800);
final aspectRatio = 3 / 4;
final scale = 1.0;
final leaveBoxBGColor = Colors.white;
final faceIconColor = Color(0xFFFF9800);
final shadeBoxBgColor = Colors.orange[50];
final slidingBarIconColor = Colors.orange;
// final screenbgcolor = Colors.white;
final screenbgcolor =  Colors.grey[50];